# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Open Data Process Framework
email: giles@dringtech.com
description: > # this means to ignore newlines until "baseurl:"
  The Open Data Process Framework is a library of best practice for publising,
  governing and consuming Open Data.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://odpf.dring.tech" # the base hostname & protocol for your site
twitter_username: dringtech
github_username:  dringtech

# Build settings
markdown: kramdown

# Collections of processes, artifacts, tasks
collections:
  processes:
    output: true
    permalink: /process/:path/
  artifacts:
    output: true
    permalink: /artifact/:path/
  tasks:
    output: true
    permalink: /task/:path/

# Set defaults for collections
defaults:
  - scope:
      path: ""
      type: processes
    values:
      layout: process
  - scope:
      path: ""
      type: artifacts
    values:
      layout: artifact
  - scope:
      path: ""
      type: tasks
    values:
      layout: task

gems:
  - jekyll-sitemap
